apiVersion: v1
kind: Service
metadata:
  name: julia-systemone-api
  labels:
    app.kubernetes.io/name: julia-systemone-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: julia-systemone-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
