apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: proxmox-exporter
  labels:
    app.kubernetes.io/name: proxmox-exporter
    app.kubernetes.io/instance: proxmox-exporter
spec:
  jobName: proxmox-exporter
  relabelings:
    - targetLabel: job
      replacement: "proxmox-exporter"
  staticConfigs:
    - targets:
        - "proxmox-exporter.proxmox-exporter.svc:8080"
