apiVersion: v1
kind: Service
metadata:
  name: image-generation-webui
  labels:
    app.kubernetes.io/name: image-generation-webui
    app.kubernetes.io/part-of: llm-gateway
spec:
  selector:
    app.kubernetes.io/name: image-generation-webui
  ports:
    - name: http
      port: 3000
      targetPort: http
