apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: http://pajikos.github.io/home-assistant-helm-chart/
      chart: home-assistant
      targetRevision: 0.3.24
      helm:
        valuesObject:
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi
          ingress:
            enabled: true
            className: nginx
            annotations:
              nginx.ingress.kubernetes.io/proxy-body-size: "64m"
            hosts:
              - host: home.chik4ge.me
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - home.chik4ge.me
          persistence:
            enabled: true
            storageClass: mayastor-3-replica
            size: 20Gi
          configuration:
            enabled: true
            forceInit: true
            templateConfig: |-
              # Loads default set of integrations. Do not remove.
              default_config:

              http:
                use_x_forwarded_for: true
                trusted_proxies:
                  - 127.0.0.1
                  - 10.244.0.0/16

              # Load frontend themes from the themes folder
              frontend:
                themes: !include_dir_merge_named themes

              automation: !include automations.yaml
              script: !include scripts.yaml
              scene: !include scenes.yaml

    - repoURL: https://charts.derwitt.dev
      chart: home-assistant-matter-server 
      targetRevision: 3.1.1
      networkInterface: net0
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
      persistence:
        storageClassName: mayastor-3-replica
        size: 2Gi
  destination:
    namespace: home-assistant
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
