apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./apps/argocd/app.yaml
  - ./apps/monitoring/metrics-server/app.yaml
  - ./apps/monitoring/node-exporter/app.yaml
  - ./apps/networking/cilium/app.yaml
  - ./apps/networking/cloudflared/app.yaml
  - ./apps/secrets/cert-manager/app.yaml
  - ./apps/secrets/external-secrets/app.yaml
  - ./apps/secrets/trust-manager/app.yaml
  - ./apps/storage/minio-operator/app.yaml
  - ./apps/storage/minio/app.yaml
  - ./apps/storage/openebs/app.yaml
