apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./apps/argocd/app.yaml
  - ./apps/external-secrets/app.yaml
  - ./apps/networking/cilium/app.yaml
  - ./apps/networking/cloudflared/app.yaml
