apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://operator.min.io/
    chart: operator
    targetRevision: 7.1.1
  destination:
    namespace: minio-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
