apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-bitwarden
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/external-secrets
    repoURL: https://github.com/chik4ge-homelab/homelab-applications
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
