apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.1.0
      helm:
        parameters:
          - name: alloy.clustering.enabled
            value: "true"
          - name: alloy.configMap.content
            value: |
              discovery.kubernetes "pods" {
                role = "pod"
              }

              discovery.kubernetes "services" {
                role = "service"
              }

              discovery.kubernetes "nodes" {
                role = "node"
              }

              discovery.relabel "pods" {
                targets = discovery.kubernetes.pods.targets

                rule {
                  source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_scrape"]
                  separator = ";"
                  regex = "true"
                  action = "keep"
                }

                rule {
                  source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
                  separator = ";"
                  regex = "(.+)"
                  target_label = "__metrics_path__"
                  replacement = "$$1"
                  action = "replace"
                }

                rule {
                  source_labels = ["__address__", "__meta_kubernetes_pod_annotation_prometheus_io_port"]
                  separator = ";"
                  regex = `([^:]+)(?::\\d+)?;(\\d+)`
                  target_label = "__address__"
                  replacement = "$$1:$$2"
                  action = "replace"
                }

                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  action = "replace"
                  target_label = "namespace"
                }

                rule {
                  source_labels = ["__meta_kubernetes_pod_name"]
                  action = "replace"
                  target_label = "pod"
                }

                rule {
                  source_labels = ["__meta_kubernetes_pod_container_name"]
                  action = "replace"
                  target_label = "job"
                }

                rule {
                  source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
                  action = "replace"
                  target_label = "app"
                }
              }

              discovery.relabel "services" {
                targets = discovery.kubernetes.services.targets

                rule {
                  source_labels = ["__meta_kubernetes_service_annotation_prometheus_io_scrape"]
                  separator = ";"
                  regex = "true"
                  action = "keep"
                }

                rule {
                  source_labels = ["__meta_kubernetes_service_annotation_prometheus_io_path"]
                  separator = ";"
                  regex = "(.+)"
                  target_label = "__metrics_path__"
                  replacement = "$$1"
                  action = "replace"
                }

                rule {
                  source_labels = ["__address__", "__meta_kubernetes_service_annotation_prometheus_io_port"]
                  separator = ";"
                  regex = `([^:]+)(?::\\d+)?;(\\d+)`
                  target_label = "__address__"
                  replacement = "$$1:$$2"
                  action = "replace"
                }
              }

              prometheus.scrape "pods" {
                targets = discovery.relabel.pods.output
                forward_to = [prometheus.remote_write.default.receiver]
              }

              prometheus.scrape "services" {
                targets = discovery.relabel.services.output
                forward_to = [prometheus.remote_write.default.receiver]
              }

              prometheus.scrape "nodes" {
                targets = discovery.kubernetes.nodes.targets
                scheme     = "https"
                bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
                tls_config {
                  insecure_skip_verify = true
                }
                forward_to = [prometheus.remote_write.default.receiver]
              }

              prometheus.operator.servicemonitors "servicemonitors" {
                forward_to = [prometheus.remote_write.default.receiver]
              }

              discovery.relabel "cadvisor" {
                targets = discovery.kubernetes.nodes.targets

                rule {
                  replacement   = "/metrics/cadvisor"
                  target_label  = "__metrics_path__"
                }
              }

              prometheus.scrape "cadvisor" {
                targets = discovery.relabel.cadvisor.output
                scheme     = "https"
                bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
                tls_config {
                  insecure_skip_verify = true
                }
                forward_to = [prometheus.remote_write.default.receiver]
              }

              prometheus.remote_write "default" {
                endpoint {
                  url = "http://mimir-nginx.mimir.svc.cluster.local/api/v1/push"
                }
              }

              loki.source.kubernetes "pods" {
                targets = discovery.kubernetes.pods.targets
                forward_to = [loki.write.default.receiver]
              }

              loki.write "default" {
                endpoint {
                  url = "http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"
                }
              }
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-operator-crds
      targetRevision: 20.0.3
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: alloy
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
