apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.1.1
      helm:
        parameters:
          - name: alloy.clustering.enabled
            value: "true"
          - name: alloy.configMap.create
            value: "false"
          - name: alloy.configMap.name
            value: "alloy-config"
          - name: alloy.configMap.key
            value: "config.alloy"
          - name: alloy.resources.requests.cpu
            value: "50m"
          - name: alloy.resources.requests.memory
            value: "2Gi"
          - name: alloy.resources.limits.cpu
            value: "200m"
          - name: alloy.resources.limits.memory
            value: "4Gi"
          - name: alloy.podAnnotations.reloader\.stakater\.com\/search
            value: "true"
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-operator-crds
      targetRevision: 21.0.0
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/monitoring/alloy
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: alloy
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
