apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.1.1
      helm:
        valuesObject:
          alloy:
            clustering:
              enabled: true
            configMap:
              create: false
              name: alloy-config
              key: config.alloy
            resources:
              requests:
                cpu: 50m
                memory: 2Gi
              limits:
                cpu: 200m
                memory: 4Gi
            podAnnotations:
              reloader.stakater.com/search: "true"
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-operator-crds
      targetRevision: 21.0.0
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/monitoring/alloy
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: alloy
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
