apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.30.1
    helm:
      valuesObject:
        extraObjects:
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: loki-bucket-secret
              labels:
                app.kubernetes.io/part-of: argocd
            spec:
              refreshInterval: 1h
              secretStoreRef:
                name: bitwarden-secretsmanager
                kind: ClusterSecretStore
              data:
                - secretKey: AWS_ACCESS_KEY_ID
                  remoteRef:
                    key: "ac15ac14-563b-4b3e-88b2-b2d400b8cfae"
                - secretKey: AWS_SECRET_ACCESS_KEY
                  remoteRef:
                    key: "fff70b9b-bc39-4c4b-831d-b2d400b8ee26"
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 3
          schemaConfig:
            configs:
              - from: "2025-05-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          pattern_ingester:
            enabled: true
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
          ruler:
            enable_api: true
          storage:
            type: s3
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            s3:
              endpoint: myminio-hl.minio.svc.cluster.local:9000
              accessKeyId: "${AWS_ACCESS_KEY_ID}"
              secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
              insecure: false
              s3ForcePathStyle: true
              http_config:
                insecure_skip_verify: true
        minio:
          enabled: false
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 3
          extraArgs:
            - "-config.expand-env=true"
          extraEnvFrom:
            - secretRef:
                name: loki-bucket-secret
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
  destination:
    namespace: loki
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
