apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/monitoring/mimir/secrets
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 5.8.0-weekly.341
      helm:
        valuesObject:
          compactor:
            persistentVolume:
              size: 10Gi
              storageClass: mayastor-3-replica

          distributor:
            replicas: 2
            resources:
              limits:
                cpu: 500m
                memory: 4Gi
              requests:
                cpu: 200m
                memory: 4Gi

          nginx:
            replicas: 2

          ingester:
            replicas: 2
            persistentVolume:
              size: 25Gi
              storageClass: mayastor-3-replica
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: target
                          operator: In
                          values:
                            - ingester
                    topologyKey: "kubernetes.io/hostname"
                  - labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/component
                          operator: In
                          values:
                            - ingester
                    topologyKey: "kubernetes.io/hostname"
                    
          store_gateway:
            persistentVolume:
              storageClass: mayastor-3-replica
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: target
                          operator: In
                          values:
                            - store-gateway
                    topologyKey: "kubernetes.io/hostname"
                  - labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/component
                          operator: In
                          values:
                            - store-gateway
                    topologyKey: "kubernetes.io/hostname"

          chunks-cache:
            enabled: true
            replicas: 1
            allocatedMemory: 1024
            resources:
              requests:
                cpu: 100m

          alertmanager:
            persistentVolume:
              storageClass: mayastor-3-replica

          metaMonitoring:
            serviceMonitor:
              enabled: true

          index-cache:
            enabled: true
            replicas: 3
            resources:
              requests:
                cpu: 100m

          metadata-cache:
            enabled: true
            replicas: 3
            resources:
              requests:
                cpu: 100m

          results-cache:
            enabled: true
            replicas: 3
            resources:
              requests:
                cpu: 100m

          minio:
            enabled: false

          global:
            extraEnvFrom:
              - secretRef:
                  name: mimir-bucket-secret

          runtimeConfig:
            ingester_limits:
              max_ingestion_rate: 100000
            distributor_limits:
              max_ingestion_rate: 100000

          mimir:
            structuredConfig:
              common:
                storage:
                  backend: s3
                  s3:
                    endpoint: minio.minio.svc.cluster.local
                    access_key_id: "${AWS_ACCESS_KEY_ID}"
                    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
                    http:
                      insecure_skip_verify: true
              limits:
                ingestion_rate: 200000
                out_of_order_time_window: 24h
                compactor_blocks_retention_period: 720h
                max_global_series_per_user: 0
              distributor:
                remote_timeout: 30m
              server:
                http_server_read_timeout: 30m
                http_server_write_timeout: 30m
              blocks_storage:
                s3:
                  bucket_name: mimir-blocks
              alertmanager_storage:
                s3:
                  bucket_name: mimir-alertmanager
              ruler_storage:
                s3:
                  bucket_name: mimir-ruler

  destination:
    namespace: mimir
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
