apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-node-exporter
    targetRevision: 4.47.3
    helm:
      valuesObject:
        fullnameOverride: node-exporter
        service:
          annotations:
            prometheus.io/scrape: "false"
        prometheus:
          monitor:
            enabled: true
            jobLabel: node-exporter
            attachMetadata:
              node: true
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
