apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-exporter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/monitoring/proxmox-exporter
    - repoURL: https://starttoaster.github.io/proxmox-exporter
      chart: proxmox-exporter
      targetRevision: 0.2.8
      helm:
        valuesObject:
          # High Availability configuration
          replicaCount: 2
          
          # Disable Pod discovery scraping to avoid duplicates with ServiceMonitor
          podAnnotations:
            prometheus.io/scrape: "false"
          
          # Resource specifications
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 64Mi
          
          # Pod Anti-Affinity for HA
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - proxmox-exporter
                  topologyKey: kubernetes.io/hostname
          
          config:
            api_insecure: true
            secretRef:
              name: proxmox-secret
          serviceMonitor:
            enabled: false

  destination:
    namespace: proxmox-exporter
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
