apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: litellm-image-generation-upstream
  labels:
    app.kubernetes.io/name: litellm-proxy
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: litellm-proxy
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: llm-gateway
            k8s:app.kubernetes.io/name: image-generation-webui
      toPorts:
        - ports:
            - port: "4000"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: llm-gateway
            k8s:app.kubernetes.io/name: image-generation-api
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
