apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: litellm-audit-user
spec:
  store: default
  clusterNamespace: rook-ceph
  displayName: litellm-audit-user
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: llm-api-logs
spec:
  bucketName: llm-api-logs
  storageClassName: ceph-bucket
  additionalConfig:
    bucketOwner: litellm-audit-user
