apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-metrics
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  endpoints:
    - port: https-minio
      path: /minio/metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      interval: 30s
