apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  protocol: nvmf
  repl: "1"
allowVolumeExpansion: true
provisioner: io.openebs.csi-mayastor
