apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-secret
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: PROXMOX_EXPORTER_PROXMOX_ENDPOINTS
      remoteRef:
        key: "Proxmox exporter Credentials"
        property: endpoints
    - secretKey: PROXMOX_EXPORTER_PROXMOX_TOKEN
      remoteRef:
        key: "Proxmox exporter Credentials"
        property: token
    - secretKey: PROXMOX_EXPORTER_PROXMOX_TOKEN_ID
      remoteRef:
        key: "Proxmox exporter Credentials"
        property: token_id
