apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-secret
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: PROXMOX_EXPORTER_PROXMOX_ENDPOINTS
      remoteRef:
        key: "6e61a4bb-4226-4f6f-9306-b2d10141b1a1"
    - secretKey: PROXMOX_EXPORTER_PROXMOX_TOKEN
      remoteRef:
        key: "5cb20bb5-a16e-4585-8fba-b2d10142152b"
    - secretKey: PROXMOX_EXPORTER_PROXMOX_TOKEN_ID
      remoteRef:
        key: "2463dd2b-4f15-485f-bfe4-b2d1014208c7"
