apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/storage/openebs/pools
    - repoURL: https://openebs.github.io/openebs
      targetRevision: 4.1.2
      chart: openebs
      helm:
        valuesObject:
          mayastor:
            csi:
              node:
                initContainers:
                  enabled: false
          engines:
            local:
              lvm:
                enabled: false
              zfs:
                enabled: false
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
