apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: client_id
      remoteRef:
        key: "Tailscale Operator Client Credentials"
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: "Tailscale Operator Client Credentials"
        property: client_secret
