apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-ml-adapter-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: LITELLM_API_KEY
      remoteRef:
        key: Immich ML Adapter LiteLLM API Key
        property: password
