apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: manifests/workloads/home-assistant/home-assistant-chart

    - repoURL: https://charts.derwitt.dev
      chart: home-assistant-matter-server 
      targetRevision: 3.3.0
      helm:
        valuesObject:
          networkInterface: eth1
          nodeSelector:
            chik4ge.me/iot-access: "true"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          podAnnotations:
            descheduler.alpha.kubernetes.io/prefer-no-eviction: "true"
          persistence:
            storageClassName: ceph-rbd
            size: 2Gi

    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: manifests/workloads/home-assistant
  destination:
    namespace: home-assistant
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: "privileged"
