apiVersion: v1
kind: Service
metadata:
  name: vllm-api
  namespace: vllm
  labels:
    app.kubernetes.io/name: vllm
spec:
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - port: 8000
      targetPort: 8000
