apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-ca
  namespace: cert-manager
spec:
  isCA: true
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: homelab-ca
  secretName: homelab-ca-secret
  duration: 87600h # 24h * 365d * 10y
  renewBefore: 336h # 24h * 14d
