apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-auth
  namespace: searxng
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    name: searxng-redis-url
    template:
      engineVersion: v2
      data:
        SEARXNG_VALKEY_URL: "redis://:{{ .password }}@redis-ha-haproxy.redis.svc.cluster.local:6379/0"
  data:
    - secretKey: password
      remoteRef:
        key: "Redis Password"
        property: password
