apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mimir-bucket-secret
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "b94aa120-7bfb-4d2b-a667-b27400f147b6"
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "3fd8b826-3247-4cf6-b995-b27400f18acd"
