apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-mqtt
  namespace: home-assistant
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    name: home-assistant-mqtt
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "switchbot-mqtt"
        property: username
    - secretKey: credential
      remoteRef:
        key: "switchbot-mqtt"
        property: credential
