apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: image-generation-artifacts
  labels:
    app.kubernetes.io/name: image-generation
spec:
  bucketName: image-generation-artifacts
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 20Gi
    bucketOwner: image-generation-user
