apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yaml
  - models-pvc.yaml
  - optimizer-model-cache-pvc.yaml
  - rbac.yaml
  - deployments.yaml
  - service.yaml
  - server-cronjob.yaml
