apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/storage/democratic-csi/secrets
    - repoURL: https://democratic-csi.github.io/charts/
      chart: democratic-csi
      targetRevision: 0.15.0
      helm:
        valuesObject:
          storageClasses:
            - name: truenas-iscsi-csi
              defaultClass: true
              reclaimPolicy: Retain
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              parameters:
                fsType: ext4
          node:
            hostPID: true
            driver:
              extraEnv:
                - name: ISCSIADM_HOST_STRATEGY
                  value: nsenter
                - name: ISCSIADM_HOST_PATH
                  value: /usr/local/sbin/iscsiadm
              iscsiDirHostPath: /etc/iscsi
              iscsiDirHostPathType: ""
              localtimeHostPath: null
            livenessProbe:
              enabled: false
          driver:
            existingConfigSecret: democratic-csi-driver-config
            config:
              driver: freenas-api-iscsi
          csiDriver:
            name: truenas-iscsi
          controller:
            driver:
              enabled: true
              image:
                registry: docker.io/democraticcsi/democratic-csi
                tag: next
            livenessProbe:
              enabled: false
  destination:
    namespace: democratic-csi
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: "privileged"
