apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/storage/mayastor
    - repoURL: https://openebs.github.io/openebs
      chart: openebs
      targetRevision: 4.3.1
      helm:
        valuesObject:
          engines:
            local:
              lvm:
                enabled: false
              zfs:
                enabled: false
          mayastor:
            csi:
              node:
                initContainers:
                  enabled: false
            io_engine:
              cpuCount: "1"
              resources:
                limits:
                  hugepages2Mi: "1Gi"
                requests:
                  hugepages2Mi: "1Gi"
          loki:
            enabled: false
          alloy:
            enabled: false
  destination:
    namespace: openebs
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: "privileged"
