apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/storage/minio/secrets
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/storage/minio/monitoring
    - repoURL: https://operator.min.io/
      chart: tenant
      targetRevision: 7.1.1
      helm:
        valuesObject:
          tenant:
            configSecret:
              name: minio-tenant-config
              existingSecret: true
              accessKey:
              secretKey:
            metrics:
              enabled: true
            buckets:
              - name: mimir-blocks
              - name: mimir-alertmanager
              - name: mimir-ruler
            pools:
              - servers: 4
                name: pool-0
                size: 25Gi
                volumesPerServer: 4
            serviceMetadata:
              minioServiceLabels:
                app: minio
            certificate:
              requestAutoCert: false
              externalCertSecret:
                - name: minio-tls-secret
                  type: cert-manager.io/v1
              externalCaCertSecret:
                - name: operator-ca-tls-minio
                  type: cert-manager.io/v1
  destination:
    namespace: minio
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
