apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/storage/minio/secrets
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/storage/minio/monitoring
    - repoURL: https://operator.min.io/
      chart: tenant
      targetRevision: 7.1.1
      helm:
        valuesObject:
          tenant:
            configSecret:
              name: minio-tenant-config
              existingSecret: true
              accessKey:
              secretKey:
            metrics:
              enabled: true
            buckets:
              - name: mimir-blocks
              - name: mimir-alertmanager
              - name: mimir-ruler
              - name: loki-admin
              - name: loki-chunks
              - name: loki-ruler
              - name: cube-vanilla-backup
            pools:
              - name: pool-3
                servers: 4
                size: 50Gi
                volumesPerServer: 2
                resources:
                  requests:
                    memory: 1Gi
                    cpu: 100m
                  limits:
                    memory: 2Gi
            serviceMetadata:
              minioServiceLabels:
                app: minio
            certificate:
              requestAutoCert: false
              externalCertSecret:
                - name: minio-tls-secret
                  type: cert-manager.io/v1
              externalCaCertSecret:
                - name: operator-ca-tls-minio
                  type: cert-manager.io/v1
          ingress:
            api:
              enabled: true
              ingressClassName: tailscale
              host: ""
              tls:
                - hosts:
                  - minio
            console:
              enabled: true
              ingressClassName: nginx
              host: minio-console.chik4ge.me
              tls:
                - hosts:
                  - minio-console.chik4ge.me
  destination:
    namespace: minio
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
