apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: pxc-operator
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.17.0
    helm:
      parameters:
        - name: replicaCount
          value: "1"
        - name: watchAllNamespaces
          value: "true"
  destination:
    namespace: percona-operator
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
