apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://1password.github.io/connect-helm-charts
      chart: connect 
      targetRevision: 2.0.2
      helm:
        valuesObject:
          connect:
            replicas: 2
            api:
              resources:
                limits:
                  memory: 128Mi
                requests:
                  cpu: 200m
                  memory: 64Mi
            sync:
              resources:
                limits:
                  memory: 64Mi
                requests:
                  cpu: 50m
                  memory: 32Mi
            applicationName: onepassword-connect
            credentialsName: op-credentials
            credentialsKey: 1password-credentials.json
            affinity: 
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - onepassword-connect
                    topologyKey: kubernetes.io/hostname
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: onepassword-connect
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
