apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/secrets/cert-manager
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.18.1
      helm:
        parameters:
          - name: crds.enabled
            value: "true"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        certmanager.k8s.io/disable-validation: "true"
