apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/secrets/cert-manager
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.19.1
      helm:
        parameters:
          - name: crds.enabled
            value: "true"
        valuesObject:
          global:
            resources:
              requests:
                cpu: 5m
                memory: 64Mi
              limits:
                memory: 128Mi
          cainjector:
            resources:
              requests:
                cpu: 5m
                memory: 80Mi
              limits:
                memory: 160Mi
          webhook:
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 64Mi
          startupapicheck:
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        certmanager.k8s.io/disable-validation: "true"
