apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - immich-db-externalsecret.yaml
  - immich-httproute.yaml
  - immich-library-pvc.yaml
  - immich-redis-externalsecret.yaml
  - ml-adapter
