apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler-consolidation
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler/
      targetRevision: 0.37.0
      chart: descheduler
      helm:
        valuesObject:
          kind: Deployment
          deschedulingInterval: 2m
          service:
            enabled: true
          serviceMonitor:
            enabled: true
          deschedulerPolicy:
            nodeSelector: '!node-role.kubernetes.io/control-plane,!chik4ge.me/iot-access,!intel.feature.node.kubernetes.io/gpu,!nvidia.com/gpu.count'
            maxNoOfPodsToEvictPerNode: 1
            maxNoOfPodsToEvictTotal: 1
            profiles:
              - name: general-pool-consolidation
                pluginConfig:
                  - name: DefaultEvictor
                    args:
                      nodeFit: true
                      nodeSelector: '!node-role.kubernetes.io/control-plane,!chik4ge.me/iot-access,!intel.feature.node.kubernetes.io/gpu,!nvidia.com/gpu.count'
                      noEvictionPolicy: Mandatory
                      podProtections:
                        defaultDisabled: []
                        extraEnabled:
                          - PodsWithPVC
                  - name: HighNodeUtilization
                    args:
                      thresholds:
                        cpu: 80
                        memory: 95
                      evictionModes:
                        - OnlyThresholdingResources
                plugins:
                  deschedule:
                    disabled:
                      - "*"
                  balance:
                    enabled:
                      - HighNodeUtilization

  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
