apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler/
      targetRevision: 0.36.0
      chart: descheduler
      helm:
        valuesObject:
          kind: Deployment
          deschedulingInterval: 2m
          service:
            enabled: true
          serviceMonitor:
            enabled: true
          deschedulerPolicy:
            profiles:
              - name: homelab-policy
                pluginConfig:
                  - name: DefaultEvictor
                    args:
                      nodeFit: true
                      ignorePvcPods: false
                      podProtections:
                        defaultDisabled:
                          - PodsWithLocalStorage
                  - name: RemoveDuplicates
                    args:
                      excludeOwnerKinds:
                        - ReplicaSet
                  - name: RemovePodsViolatingNodeTaints
                    args:
                      includePreferNoSchedule: true
                plugins:
                  deschedule:
                    enabled:
                      - RemovePodsViolatingNodeTaints
                  balance:
                    enabled:
                      - RemoveDuplicates

  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
