apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/monitoring/mimir/secrets
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 5.6.0
      helm:
        valuesObject:
          global:
            extraEnvFrom:
              - secretRef:
                  name: mimir-bucket-secret
          minio:
            enabled: false
          mimir:
            structuredConfig:
              common:
                storage:
                  backend: s3
                  s3:
                    endpoint: minio.minio.svc.cluster.local
                    access_key_id: "${AWS_ACCESS_KEY_ID}"
                    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
                    http:
                      insecure_skip_verify: true
              blocks_storage:
                s3:
                  bucket_name: mimir-blocks
              alertmanager_storage:
                s3:
                  bucket_name: mimir-alertmanager
              ruler_storage:
                s3:
                  bucket_name: mimir-ruler
          ingester:
            persistentVolume:
              size: 25Gi
  destination:
    namespace: mimir
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
