apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: image-generation-user
  labels:
    app.kubernetes.io/name: image-generation
spec:
  store: default
  clusterNamespace: rook-ceph
  displayName: image-generation-user
