apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - llama-cpp
  - llama-cpp-embeddinggemma-canary
  - litellm
  - image-generation
  - image-generation-webui
  - julia-systemone-api
  - embeddinggemma-api
configMapGenerator:
  - name: llm-gateway-model-cache
    files:
      - model-cache/cache.py
      - model-cache/ornith.json
      - model-cache/optimizer.json
      - model-cache/diffuser.json
      - model-cache/embeddinggemma-2.json
  - name: julia-systemone-model-cache
    files:
      - model-cache/julia-1.json
