apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-cache
  labels:
    app.kubernetes.io/name: llm-gateway
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 40Gi
