apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-cube
  namespace: argocd
spec:
  project: default
  sources:
    # - repoURL: https://github.com/chik4ge-homelab/homelab-applications
    #   targetRevision: main
    #   path: apps/games/minecraft-cube/secrets
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/games/minecraft-cube/pvcs
    - repoURL: https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      targetRevision: 4.26.3
      helm:
        valuesObject:
          resources:
            requests:
              memory: 1Gi
              cpu: 1000m
            limits:
              memory: 1Gi
          workloadAsStatefulSet: true
          strategyType: RollingUpdate
          nodeSelector:
            kubernetes.io/hostname: k8s-w-edelweiss

          minecraftServer:
            eula: TRUE
            version: 1.21.4
            type: PAPER
            difficulty: peaceful
            announcePlayerAchievements: false
            generateStructures: false
            spawnAnimals: false
            spawnMonsters: false
            spawnNPCs: false
            spawnProtection: 0
            gameMode: creative
            motd: "Welcome to Minecraft on Kubernetes!"
            onlineMode: true
            enforceSecureProfile: true
            memory: 1G
            serviceType: LoadBalancer
            loadBalancerClass: tailscale

          rcon:
            enabled: false # TODO: enable rcon

          mcbackup:
            enabled: false # TODO: enable mcbackup

          # envFrom: # TODO: enable envFrom whitelist

          persistence:
            dataDir:
              enabled: true
              existingClaim: minecraft-cube-vanilla-pvc
  destination:
    namespace: minecraft-cube
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
