apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-backup-externalsecrets
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: access-key-id
      remoteRef:
        key: "a13e68c4-7915-4503-8499-b2e100b23217"
    - secretKey: secret-access-key
      remoteRef:
        key: "d1c2ab54-ddb1-4fe1-8e84-b2e100b243bb"
    - secretKey: endpoint
      remoteRef:
        key: "0b567ee3-d0ad-44b7-930c-b2e100b28cd1"
