apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-backup-externalsecrets
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: access-key-id
      remoteRef:
        key: "Talos Backup s3 Credentials"
        property: accessKey
    - secretKey: secret-access-key
      remoteRef:
        key: "Talos Backup s3 Credentials"
        property: secretKey
    - secretKey: endpoint
      remoteRef:
        key: "Talos Backup s3 Credentials"
        property: URL
