apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.longhorn.io/
    chart: longhorn
    targetRevision: v1.7.2
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
