apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://operator.min.io/
    chart: tenant
    targetRevision: 7.0.0
    helm:
      parameters:
        - name: tenant.pools[0].name
          value: pool-0
        - name: tenant.pools[0].size
          value: 5Gi
        - name: tenant.pools[0].volumesPerServer
          value: "3"
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
