apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/chik4ge-homelab/mysql-operator
    targetRevision: main
  destination:
    namespace: mysql-operator
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apiextensions.k8s.io
    jsonPointers:
    - /spec
    kind: CustomResourceDefinition
    name: innodbclusters.mysql.oracle.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
