# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-driver-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-iscsi
          instance_id:
          httpConnection:
            protocol: http
            host: truenas.serval-great.ts.net
            port: 80
            apiKey: {{ .apiToken }}
            allowInsecure: true
          sshConnection:
            host: truenas.serval-great.ts.net
            port: 22
            username: {{ .sshUser}}
            password: {{ .sshPassword }}
          zfs:
            cli:
              sudoEnabled: true
            datasetParentName: tank/k8s-pvs
            detachedSnapshotsDatasetParentName: tanks/k8s-snaps
          iscsi:
            targetPortal: "truenas.serval-great.ts.net:3260"
            namePrefix: csi-
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
                targetGroupAuthGroup:
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 512
            extentRpm: "SSD"
            extentAvailThreshold: 0
          node:
            mount:
              checkFileSystem:
                xfs:
                  enabled: false
                  customOptions: []
                ext4:
                  enabled: false
                  customOptions: []
                  customFilesystemOptions: []
                btrfs:
                  enabled: false
                  customOptions: []
                  customFilesystemOptions: []
  data:
    - secretKey: apiToken
      remoteRef:
        key: "af8b00ba-bb57-457e-8f63-b29101145c40"
    - secretKey: sshUser
      remoteRef:
        key: "b3c71d57-8aca-4bc9-8f02-b29c0112f37e"
    - secretKey: sshPassword
      remoteRef:
        key: "4022c630-40c0-41c2-8ee9-b29c01131ec6"
  