# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-driver-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-iscsi
          instance_id:
          httpConnection:
            protocol: http
            host: 192.168.0.200
            port: 80
            apiKey: {{ .apiToken }}
            allowInsecure: true
          sshConnection:
            host: 192.168.0.200
            port: 22
            username: {{ .sshUser}}
            password: {{ .sshPassword }}
          zfs:
            cli:
              sudoEnabled: true
              paths:
                sudo: /usr/bin/sudo
            datasetParentName: tank/k8s-pvs
            detachedSnapshotsDatasetParentName: tank/k8s-snaps
          iscsi:
            targetPortal: "192.168.0.200:3260"
            namePrefix: csi-
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
                targetGroupAuthGroup:
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 512
            extentRpm: "SSD"
            extentAvailThreshold: 0
          node:
            mount:
              checkFileSystem:
                xfs:
                  enabled: false
                  customOptions: []
                ext4:
                  enabled: false
                  customOptions: []
                  customFilesystemOptions: []
                btrfs:
                  enabled: false
                  customOptions: []
                  customFilesystemOptions: []
  data:
    - secretKey: apiToken
      remoteRef:
        key: "democratic-csi TrueNAS Token"
        property: token
    - secretKey: sshUser
      remoteRef:
        key: "democratic-csi User"
        property: username
    - secretKey: sshPassword
      remoteRef:
        key: "democratic-csi User"
        property: password
