# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-driver-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          instance_id:
          httpConnection:
            protocol: http
            host: truenas.serval-great.ts.net
            port: 80
            apiKey: {{ .apiToken }}
            allowInsecure: true
          zfs:
            datasetParentName: tank/k8s-pvs
            detachedSnapshotsDatasetParentName: tanks/k8s-snaps
          iscsi:
            targetPortal: "truenas.serval-great.ts.net:3260"
            namePrefix: csi-
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
                targetGroupAuthGroup:
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 512
            extentRpm: "SSD"
            extentAvailThreshold: 0
  data:
    - secretKey: apiToken
      remoteRef:
        key: "af8b00ba-bb57-457e-8f63-b29101145c40"
  