apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    name: litellm-db-credentials
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: LiteLLM Proxy Credentials
        property: db_username
    - secretKey: password
      remoteRef:
        key: LiteLLM Proxy Credentials
        property: db_password
