apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: clientId
      remoteRef:
        key: "0fe26c91-c496-4b89-ae0a-b2dc00fb6f0f"
    - secretKey: clientSecret
      remoteRef:
        key: "fc2d8162-5068-4f8c-9024-b2dc00fb79fb"
