apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-discord-webhook
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
    - secretKey: discord-webhook-url
      remoteRef:
        key: "28cb2c58-23e7-46b3-b1ff-b2eb00c5988c"
