apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-secret
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: "cc8fde02-d3af-46cf-b5db-b26a010d4be1"
