apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-tenant-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: config.env
      remoteRef:
        key: "Minio config.env"
        property: notesPlain
