apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-tenant-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: config.env
      remoteRef:
        key: "ea37fc0c-7d59-4eef-b7f2-b27400db3dbf"
