apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
  namespace: cert-manager
spec:
  dnsNames:
    - "minio.minio"
    - "minio.minio.svc"
    - "minio.minio.svc.cluster.local"
    - "*.minio.minio.svc.cluster.local"
    - "*.myminio-hl.minio.svc.cluster.local"
    - "*.myminio.minio.minio.svc.cluster.local"
  secretName: minio-tls-secret
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
