apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: /tmp/kustomize-helm-home

helmCharts:
  - name: home-assistant
    repo: http://pajikos.github.io/home-assistant-helm-chart/
    version: 0.3.61
    releaseName: home-assistant
    namespace: home-assistant
    valuesFile: values.yaml

patches:
  - path: bluetooth-sidecar-patch.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: home-assistant
  - path: delete-test-connection-patch.yaml
    target:
      version: v1
      kind: Pod
      name: home-assistant-test-connection
