nodeSelector:
  chik4ge.me/iot-access: "true"

hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - NET_RAW

env:
  - name: DBUS_SYSTEM_BUS_ADDRESS
    value: unix:path=/run/dbus/system_bus_socket

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 1Gi

podAnnotations:
  descheduler.alpha.kubernetes.io/prefer-no-eviction: "true"

ingress:
  enabled: false

persistence:
  enabled: true
  storageClass: ceph-rbd
  size: 20Gi

additionalVolumes:
  - name: dbus-run
    emptyDir: {}
  - name: usb-bus
    hostPath:
      path: /dev/bus/usb
      type: Directory

additionalMounts:
  - name: dbus-run
    mountPath: /run/dbus
  - name: usb-bus
    mountPath: /dev/bus/usb

configuration:
  enabled: true
  forceInit: true
  templateConfig: |-
    # Loads default set of integrations. Do not remove.
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 127.0.0.1
        - 10.244.0.0/16

    prometheus:
      requires_auth: false

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

serviceMonitor:
  enabled: true
  scrapeInterval: 5m
