apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/networking/external-dns
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns 
      targetRevision: 1.19.0
      helm:
        valuesObject:
          provider: cloudflare
          policy: sync
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-token-secret
                  key: api-token
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
