apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/chik4ge-homelab/homelab-applications
    targetRevision: main
    path: apps/networking/nginx-ingress
  - repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.2
    helm:
      valuesObject:
        controller:
          service:
            loadBalancerClass: tailscale
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 90Mi
          extraArgs:
            default-ssl-certificate: "nginx-ingress/wildcard-chik4ge-me-tls"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
