apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.2
    helm:
      valuesObject:
        controller:
          loadBalancerClass: tailscale
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 90Mi
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
