apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pve-lb
  namespace: argocd
spec:
  project: default
  source:
    path: apps/networking/pve-lb
    repoURL: https://github.com/chik4ge-homelab/homelab-applications
    targetRevision: main
  destination:
    namespace: pve-lb
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
