apiVersion: v1
kind: Service
metadata:
  name: embeddinggemma-vllm-test
  labels:
    app.kubernetes.io/name: embeddinggemma-vllm-test
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: embeddinggemma-vllm-test
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
