apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.9.0
    helm:
      valuesObject:
        replicas: 1
        grafana.ini:
          server:
            root_url: https://grafana.chik4ge.me
            enable_gzip: true
          auth:
            disable_login_form: true
          auth.github:
            enabled: true
            allow_sign_up: true
            client_id: Ov23liEAZPnCVaDnDWdl
            client_secret: $__env{GF_GITHUB_CLIENT_SECRET}
            scopes: user:email,read:org
            auth_url: https://github.com/login/oauth/authorize
            token_url: https://github.com/login/oauth/access_token
            api_url: https://api.github.com/user
            allow_assign_grafana_admin: true
            role_attribute_path: "contains(groups[*], '@chik4ge-homelab/admin') && 'GrafanaAdmin' || 'Viewer'"
        envValueFrom:
          GF_GITHUB_CLIENT_SECRET:
            secretKeyRef:
              name: grafana-secret
              key: github-sso-client-secret

        extraObjects:
          - apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: grafana-secret
              labels:
                app.kubernetes.io/part-of: argocd
            spec:
              refreshInterval: 1h
              secretStoreRef:
                name: bitwarden-secretsmanager
                kind: ClusterSecretStore
              data:
                - secretKey: github-sso-client-secret
                  remoteRef:
                    key: "f7b7d08e-0571-4685-a889-b275010f851f"

  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
