apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/storage/minio/secrets
    - repoURL: https://operator.min.io/
      chart: tenant
      targetRevision: 7.0.0
      helm:
        valuesObject:
          tenant:
            configuration:
              name: minio-tenant-config
            configSecret:
              existingSecret: true
              accessKey: null
              secretKey: null
            buckets:
              - name: mimir-blocks
              - name: mimir-alertmanager
              - name: mimir-ruler
        parameters:
          - name: tenant.pools[0].name
            value: pool-0
          - name: tenant.pools[0].size
            value: 5Gi
          - name: tenant.pools[0].volumesPerServer
            value: "3"
          - name: tenant.pools[0].storageClassName
            value: ""
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
