apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/devops/argocd
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 8.0.10
      chart: argo-cd
      helm:
        valuesObject:
          global:
            addPrometheusAnnotations: true
          configs:
            cm:
              url: https://argocd.chik4ge.me
              dex.config: |
                connectors:
                  - type: github
                    id: github
                    name: GitHub
                    config:
                      clientID: Ov23liO6LEyYow0nlys8
                      clientSecret: $github-secret:token
                      orgs:
                        - name: chik4ge-homelab
              resource.exclusions: |
                - apiGroups:
                    - cilium.io
                  kinds:
                    - CiliumIdentity
                  clusters:
                    - "*"
            rbac:
              policy.csv: |
                g, chik4ge-homelab:admin, role:admin
          redis-ha:
            enabled: true
            haproxy:
              metrics:
                enabled: true

          controller:
            replicas: 1
            metrics:
              enabled: true

          server:
            replicas: 2
            metrics:
              enabled: true

          repoServer:
            replicas: 2
            metrics:
              enabled: true

          applicationSet:
            replicas: 2
            metrics:
              enabled: true

          dex:
            metrics:
              enabled: true

          redis:
            metrics:
              enabled: true
              
          notifications:
            enabled: true
            metrics:
              enabled: true
            cm:
              create: false
            secret:
              create: false
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
