apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/devops/argocd
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 8.3.5
      chart: argo-cd
      helm:
        valuesObject:
          global:
            domain: argocd.chik4ge.me
            addPrometheusAnnotations: true
            deploymentStrategy:
              type: RollingUpdate
              rollingUpdate:
                maxSurge: 0
                maxUnavailable: 1
          configs:
            cm:
              url: https://argocd.chik4ge.me
              dex.config: |
                connectors:
                  - type: github
                    id: github
                    name: GitHub
                    config:
                      clientID: Ov23liO6LEyYow0nlys8
                      clientSecret: $github-secret:token
                      orgs:
                        - name: chik4ge-homelab
              resource.exclusions: |
                - apiGroups:
                    - cilium.io
                  kinds:
                    - CiliumIdentity
                  clusters:
                    - "*"
              resource.customizations.ignoreDifferences.apps_Deployment: |
                jqPathExpressions:
                  - .spec.template.metadata.annotations."kubectl.kubernetes.io/restartedAt"
                  - if (.spec.template.metadata.annotations | length) == 0 then .spec.template.metadata.annotations else empty end
            rbac:
              policy.csv: |
                g, chik4ge-homelab:admin, role:admin
          redis-ha:
            enabled: true
            haproxy:
              metrics:
                enabled: true
              resources:
                requests:
                  cpu: 5m
                  memory: 64Mi
                limits:
                  memory: 128Mi
            redis:
              resources:
                requests:
                  cpu: 20m
                  memory: 32Mi
                limits:
                  memory: 128Mi
            sentinel:
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  memory: 128Mi
            splitBrainDetection:
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  memory: 64Mi

          controller:
            replicas: 1
            metrics:
              enabled: true
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi

          server:
            replicas: 2
            metrics:
              enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 80Mi
              limits:
                memory: 128Mi
            ingress:
              enabled: true
              ingressClassName: nginx

          repoServer:
            replicas: 2
            metrics:
              enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 80Mi
              limits:
                memory: 512Mi

          applicationSet:
            replicas: 2
            metrics:
              enabled: true
            resources:
              requests:
                cpu: 5m
                memory: 150Mi
              limits:
                memory: 200Mi

          dex:
            metrics:
              enabled: true
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 256Mi

          redis:
            metrics:
              enabled: true
              
          notifications:
            enabled: true
            metrics:
              enabled: true
            resources:
              requests:
                cpu: 5m
                memory: 48Mi
              limits:
                memory: 64Mi
            cm:
              create: false
            secret:
              create: false
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
