apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: v1.4.2
    helm:
      valuesObject:
        reloader:
          deployment:
            resources:
              limits:
                cpu: 150m
                memory: 512Mi
              requests:
                cpu: 10m
                memory: 128Mi
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
