apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.17.3
      helm:
        parameters:
          - name: ipam.mode
            value: kubernetes
          - name: kubeProxyReplacement
            value: "true"
          - name: l2announcements.enabled
            value: "true"
          - name: securityContext.capabilities.ciliumAgent
            value: "{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
          - name: securityContext.capabilities.cleanCiliumState
            value: "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
          - name: cgroup.autoMount.enabled
            value: "false"
          - name: cgroup.hostRoot
            value: /sys/fs/cgroup
          - name: k8sServiceHost
            value: localhost
          - name: k8sServicePort
            value: "7445"
          - name: routingMode
            value: "native"
          - name: socketLB.hostNamespaceOnly
            value: "true"
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/networking/cilium/l2announce
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
