apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./bundles/bundle.yaml
  - ./secret-stores/secret-store.yaml
  - https://raw.githubusercontent.com/external-secrets/bitwarden-sdk-server/refs/tags/v0.3.1/hack/bitwarden-certificate.yaml
  - https://raw.githubusercontent.com/external-secrets/bitwarden-sdk-server/refs/tags/v0.3.1/hack/cluster_issuer.yaml

patches:
  - target:
      kind: Certificate
      name: bitwarden-bootstrap-certificate
      namespace: cert-manager
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - bitwarden-sdk-server.external-secrets.svc.cluster.local
          - external-secrets-bitwarden-sdk-server.external-secrets.svc.cluster.local
          - localhost
  - target:
      kind: Certificate
      name: bitwarden-tls-certs
      namespace: default
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: external-secrets
      - op: replace
        path: /spec/dnsNames
        value:
          - bitwarden-sdk-server.external-secrets.svc.cluster.local
          - external-secrets-bitwarden-sdk-server.external-secrets.svc.cluster.local
          - localhost
  # Reloader annotations for automatic restart on certificate/configmap changes
  - target:
      kind: Deployment
      name: external-secrets
      namespace: external-secrets
    patch: |-
      - op: add
        path: /metadata/annotations/configmap.reloader.stakater.com~1reload
        value: bitwarden-trust-bundle
  - target:
      kind: Deployment
      name: bitwarden-sdk-server
      namespace: external-secrets
    patch: |-
      - op: add
        path: /metadata/annotations/secret.reloader.stakater.com~1reload
        value: bitwarden-tls-certs
