apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-embeddinggemma-canary-model-cache
  labels:
    app.kubernetes.io/name: llama-cpp-embeddinggemma-canary
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
