apiVersion: v1
kind: Service
metadata:
  name: llama-cpp-embeddinggemma-canary
  labels:
    app.kubernetes.io/name: llama-cpp-embeddinggemma-canary
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: llama-cpp-embeddinggemma-canary
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
