apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-sdk
spec:
  provider:
    onepasswordSDK:
      vault: homelab
      auth:
        serviceAccountSecretRef:
          name: onepassword-connect-token-homelab
          key: token
          namespace: external-secrets
      integrationInfo:
        name: integration-info
        version: v1
