apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets/driver-config-secret.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: democratic-csi-node
      namespace: democratic-csi
    patch: |-
      - op: add
        path: /spec/template/spec/containers/2/livenessProbe/timeoutSeconds
        value: 30
      - op: add
        path: /spec/template/spec/containers/2/livenessProbe/initialDelaySeconds
        value: 30
      - op: add
        path: /spec/template/spec/containers/2/livenessProbe/periodSeconds
        value: 10
      - op: add
        path: /spec/template/spec/containers/2/livenessProbe/failureThreshold
        value: 3