apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.7.16
    chart: argo-cd
    helm:
      valuesObject:
        configs:
          cm:
            url: https://argocd.chik4ge.me
          # params:
          #   server.insecure: true
          rbac:
            policy.csv: |
              g, chik4ge-homelab:admin, role:admin
        dex.config: |
          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                clientID: Ov23liO6LEyYow0nlys8
                clientSecret: $github-secret:token
                orgs:
                  - name: chik4ge-homelab
        resource.exclusions: |
          - apiGroups:
              - cilium.io
            kinds:
              - CiliumIdentity
            clusters:
              - "*"
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
