apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: apps/argocd/secrets
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.7.17
      chart: argo-cd
      helm:
        valuesObject:
          configs:
            cm:
              url: https://argocd.chik4ge.me
              dex.config: |
                connectors:
                  - type: github
                    id: github
                    name: GitHub
                    config:
                      clientID: Ov23liO6LEyYow0nlys8
                      clientSecret: $github-secret:token
                      orgs:
                        - name: chik4ge-homelab
              resource.exclusions: |
                - apiGroups:
                    - cilium.io
                  kinds:
                    - CiliumIdentity
                  clusters:
                    - "*"
            rbac:
              policy.csv: |
                g, chik4ge-homelab:admin, role:admin
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
